global:
  scrape_interval: 15s

scrape_configs:
  - job_name: debts-api
    static_configs:
      - targets: ["debts-api:8080"]

  - job_name: credit-score-api
    static_configs:
      - targets: ["credit-score-api:8080"]