global:
  scrape_interval: 15s

scrape_configs:
  - job_name: debts-api
    static_configs:
      - targets: ["host.docker.internal:5235"]  # Mac/Windows

  - job_name: credit-score-api
    static_configs:
      - targets: ["host.docker.internal:5017"]