apiVersion: v1
kind: ConfigMap
metadata:
  name: debts-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__Default: "server=192.168.49.3;port=3306;database=debtdb;user=root;password=root"
  Redis__ConnectionString: "192.168.49.4:6379"
  Kafka__BootstrapServers: "kafka:19092"
  RabbitMQ__Host: "192.168.49.6"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
  Email__Host: "192.168.49.8"
  Email__Port: "1025"
  Email__From: "noreply@debts.com"
  CreditScore__GrpcUrl: "http://credit-score-api:5018"
  OpenTelemetry__Endpoint: "http://192.168.49.7:4317"