apiVersion: v1
kind: Secret
metadata:
  name: debts-api-secret
type: Opaque
stringData:
  Jwt__Key: "super-secret-key-with-many-characters"
  Auth__Pepper: "un-secreto-largo-y-random-que-solo-vive-en-config"