// <auto-generated />
using System;
using CreditScore.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CreditScore.Api.Migrations
{
    [DbContext(typeof(CreditScoreDbContext))]
    partial class CreditScoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CreditScore.Api.Entities.CreditHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ActiveDebts")
                        .HasColumnType("int");

                    b.Property<int>("LowNegotiations")
                        .HasColumnType("int");

                    b.Property<DateTime>("OldestDebtDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SettledDebts")
                        .HasColumnType("int");

                    b.Property<int>("TotalDebts")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalNegotiatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("CreditHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
